language: groovy
jdk:
- openjdk8
sudo: false
addons:
  apt:
    packages:
    - gdal-bin
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew clean && ./gradlew war"
deploy:
  provider: releases
  api_key:
    secure: PtPyhBC5Ln3r5bU+SNOKfttSJ28Z/Pg1xi4edadmT6OVCmnktksoc/odBFoGvJ+rzOFceU5LVegude4lCNKpjclrhdu2Pde0cz3P5XxMpJ/TGJhDj9VysCKMmhI+pXIwxUC2Gc90YGqcG5/EveqPpRbxs5iuf61YveNBultPR4jYkyiEDiCAh1I98AfLAY/wOHopx/fpGJDfAHUi/1NxQbNkdV3Z5QrZO99FGWr6mIqxti7U3+1zL7tmF92JPNhxDkSjZBwlFfaeP5R/C1PqvjVUYl8E4nN2PuGVma5FmN1ZJwGhFoUUMcRq4qoflGJBjVtaCsHGulKkZo6d7oXEp5TMJJ4u5oIREtMEeOqpHH7c2IlvsIYoJtgTfWJP7SHeYgeWTSACTJxbcA4HHuJTe5xEamKFOxEH4Ck4pBiIZQHY8oqF2/IfdRQlzbO59+dqQZiksxaSXyWEEg5Ee77P4lO4X6677qUQg9Ub0Mm2Ktp8ucHRzu45xkJEV5tB2BFH7dsr/nqTkBgIk73g92PcMZKTxX9yQH93eI48ukOko8t8w5mTTm5sxC4YxA1zWED3ssBwGNKUgiSOV0kVDrnot0H82xG2cfPKHNBcD2c96NG3MkKg7sy32UGQCHS0BYMxcylMWyLCyC5m27NUQ/B2MLDBy6FFkD4SchjWPeEhrjg=
  file_glob: true
  file: build/libs/spatial-service-*.war
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/spatial-service
    all-branches: true
    tags: true
